name: spaship operator build and push into container repo

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '*'
  workflow_dispatch:
    inputs:
      env:
        description: Select envirinment
        options:
          - Dev
          - Qa
          - Stage
        required: true
        type: choice
jobs:

  prebuild:
    runs-on: ubuntu-latest
    name: Prebuild Test
    steps:
      - name: Test echo workflow input
        run: echo "Hola ${{ github.event.inputs.env }}"